(setq-default word-wrap t)
(setq-default line-spacing 0)
(setq x-underline-at-descent-line t)
(setq-default  tooltip-mode nil)
(setq-default  cursor-type 'bar)
(set-cursor-color "#ffffff")
(setq blink-cursor-mode nil)
(setq pop-up-windows nil)
(tool-bar-mode -1)
(menu-bar-mode 1)
(toggle-scroll-bar 1)
(display-time-mode 1)
(display-battery-mode 1)
