(set-language-environment "UTF-8")
(put 'set-goal-column 'disabled nil)
(setq version-control t)
(setq backup-directory-alist  '(("." . "~/.emacs.d/file-backups")))
(setq initial-major-mode 'org-mode)